// SHIPPING
export const CABA_FREE_SHIPPING_MIN_SUBTOTAL_REQUIRED = 10000;
export const CABA_SHIPPING_FEE = 500;
export const BUENOS_AIRES_FREE_SHIPPING_MIN_SUBTOTAL_REQUIRED = 15000;
export const BUENOS_AIRES_SHIPPING_FEE = 1000;

// DISCOUNT
export const CASH_DISCOUNT_PERCENT = 10;
